apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni.lcars.tankbusta.com:8100/
    name: omni-lcars-prod
contexts:
  - context:
      cluster: omni-lcars-prod
      namespace: default
      user: omni-lcars-prod-cschmitt@tankbusta.net
    name: omni-lcars-prod
current-context: omni-lcars-prod
users:
- name: omni-lcars-prod-cschmitt@tankbusta.net
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.lcars.tankbusta.com/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:lcars-prod
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
